# Base information
baseURL = "https://kaishuun.github.io/kevinhe.github.io/"
languageCode = "en-gb"
title = "Kevin He"
theme = "dev-portfolio"
googleAnalytics = ""
canonifyURLs = true
# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About + Resume"
  URL = "about"
  weight=1

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight=3



[params]
home = "Home"
# Meta data
description = "This is the Portfolio Website of Kevin He, an Operations Research Student at Simon Fraser University"
author = "Kevin He"



  [params.footer]
  email = "sjhe@sfu.ca"
  address = "Surrey, BC"


[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

